import { CATEGORYFILEPATH, CUSTOMATTRIBUTE, CUSTOMATTRIBUTELIST, JSONEXTENSION, SETTINGFILEPATH, TRANSACTION } from "../../../Constant";

//カテゴリIDの接頭辞
export const PRE_CATEGORY_ID = `CATEGORY-`;
//メニューファイルのパス
export const CATEGORY_FILEPATH = `${SETTINGFILEPATH}${CATEGORYFILEPATH}${JSONEXTENSION}`;
