import { GENERALDETAILFILEPATH, JSONEXTENSION, MASTERFILEPATH, SETTINGFILEPATH, TASKINPUTSETTING } from "../../../Common/Const.tsx/CommonConst";

//デフォルト属性ファイルのパス
export const DEFAULT_ATTRIBUTE_FILEPATH = `${SETTINGFILEPATH}${TASKINPUTSETTING}${JSONEXTENSION}`;
//汎用詳細リストファイルのパス
export const GENERALDETAIL_FILEPATH = `${MASTERFILEPATH}${GENERALDETAILFILEPATH}${JSONEXTENSION}`
