import { GENERALDETAILFILEPATH, JSONEXTENSION, MASTERFILEPATH } from "../../Common/Const/CommonConst";

//汎用詳細ファイルのパス
export const GENERAL_DETAIL_FILEPATH = `${MASTERFILEPATH}${GENERALDETAILFILEPATH}${JSONEXTENSION}`;