import { JSONEXTENSION, MEMOCONTENTSETTINGFILENM, MEMOFILENM, MEMOINPUTSETTINGFILENM, MEMOSEARCHCONDITIONFILENM, SETTINGFILEPATH, TAGFILENM, TRANSACTION } from "../../Common/Const/CommonConst";

//メモファイルのパス
export const MEMO_FILEPATH = `${TRANSACTION}${MEMOFILENM}${JSONEXTENSION}`;
//メモ検索条件ファイルのパス
export const MEMO_SEARCHCONDITION_FILEPATH = `${SETTINGFILEPATH}${MEMOSEARCHCONDITIONFILENM}${JSONEXTENSION}`;
//メモコンテンツ設定ファイルのパス
export const MEMO_CONTENT_FILEPATH = `${SETTINGFILEPATH}${MEMOCONTENTSETTINGFILENM}${JSONEXTENSION}`;
//メモ入力設定ファイルのパス
export const MEMO_INPUTSETTING_FILEPATH = `${SETTINGFILEPATH}${MEMOINPUTSETTINGFILENM}${JSONEXTENSION}`;
//メモIDの接頭辞
export const PRE_MEMO_ID = `MEMOID-`;
//メモの状態
export const MEMO_STATUS = {
    //下書き
    draft: "1",
    //登録
    regist: "2",
}
//メモ検索条件のユーザープロパティID
export const USER_SEARCHCONDITION_ID = "userId";
//タグファイルのパス
export const TAG_FILEPATH = `${TRANSACTION}${TAGFILENM}${JSONEXTENSION}`;
//タグIDの接頭辞
export const PRE_TAG_ID = `TAGID-`;