import { JSONEXTENSION, MEMOCONTENTSETTINGFILENM, MEMOFILENM, MEMOINPUTSETTINGFILENM, MEMOSEARCHCONDITIONFILENM, SETTINGFILEPATH, TRANSACTION } from "../../Common/Const/CommonConst";

//メモファイルのパス
export const MEMO_FILEPATH = `${TRANSACTION}${MEMOFILENM}${JSONEXTENSION}`;
//メモ検索条件ファイルのパス
export const MEMO_SEARCHCONDITION_FILEPATH = `${SETTINGFILEPATH}${MEMOSEARCHCONDITIONFILENM}${JSONEXTENSION}`;
//メモコンテンツ設定ファイルのパス
export const MEMO_CONTENT_FILEPATH = `${SETTINGFILEPATH}${MEMOCONTENTSETTINGFILENM}${JSONEXTENSION}`;
//メモ入力設定ファイルのパス
export const MEMO_INPUTSETTING_FILEPATH = `${SETTINGFILEPATH}${MEMOINPUTSETTINGFILENM}${JSONEXTENSION}`;
