import { CATEGORYFILEPATH, JSONEXTENSION, SETTINGFILEPATH, SUBCATEGORYFILEPATH } from "../../../Common/Const/CommonConst";

//カテゴリIDの接頭辞
export const PRE_CATEGORY_ID = `CATEGORY-`;
//メニューファイルのパス
export const CATEGORY_FILEPATH = `${SETTINGFILEPATH}${CATEGORYFILEPATH}${JSONEXTENSION}`;
//サブメニューファイルのパス
export const SUB_CATEGORY_FILEPATH = `${SETTINGFILEPATH}${SUBCATEGORYFILEPATH}${JSONEXTENSION}`;
