import { JSONEXTENSION, MEMO_PRIVATE_SEARCHCONDITION_FILEPATH, MEMOSEARCHCONDITIONFILENM, SETTINGFILEPATH, TRANSACTION } from "../../../Common/Const/CommonConst";

//メモ検索条件設定ファイルのパス
export const MEMO_PRIVATE_SEARCHCONDITION_FILE_PATH = `${TRANSACTION}${MEMO_PRIVATE_SEARCHCONDITION_FILEPATH}${JSONEXTENSION}`;
//メモ検索条件ファイルのパス
export const MEMO_SEARCHCONDITION_FILEPATH = `${SETTINGFILEPATH}${MEMOSEARCHCONDITIONFILENM}${JSONEXTENSION}`;