import { JSONEXTENSION, MEMO_PRIVATE_SEARCHCONDITION_FILEPATH, TRANSACTION } from "../../../Common/Const/CommonConst";

//メモ検索条件設定ファイルのパス
export const MEMO_PRIVATE_SEARCHCONDITION_FILE_PATH = `${TRANSACTION}${MEMO_PRIVATE_SEARCHCONDITION_FILEPATH}${JSONEXTENSION}`;